pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'print'
            }
        }
        // stage('Test') {
        //     steps {
        //         sh 'mvn test'
        //     }
        //     post {
        //         always {
        //             junit 'target/surefire-reports/*.xml'
        //         }
        //     }
        // }
        // stage('Deliver') {
        //     steps {
        //         sh './jenkins/scripts/deliver.sh'
        //     }
        // }
        // stage('complete') {
        //     steps {
        //         echo "completed"
        //     }
        //}
    }
}
